### PR TITLE
has_path function for check if path exists in dictionary

### PR DESCRIPTION
**Pull request by deniszorinets**
I sure that function for checking path existence in dict is quite useful:
for example for such cases:
```
if has_key(some_dict, ('some_key1', 'some_key2', 'some_another_key')):
    del some_dict['some_key1'][ 'some_key2']['some_another_key']
```
or for another cases when we need to be sure that some nested key exists

### CODE REVIEW

**Comment by Suor** [comment]
Hello, @deniszorinets, adding this makes sense, thanks for the idea. However, I would implement it with a for cycle it would be both simpler and faster. And I wouldn't focus on dicts only, it might work for mixed collections same as `get_in()` and friends.

**Comment by deniszorinets** [comment]
I think you are right - so I'm updated commit

**Comment by Suor** [comment]
It probably makes sense to add a del_in() too.

**Comment by Suor** [comment]
Merged, thanks

**Comment by Suor** [comment]
I am considering renaming this into `has_in()` to be more in line with the rest of the herd. What do you think?

**Comment by deniszorinets** [comment]
I think has_path is more obvious, but has_in is ok too

**Pull request merged**
