### PR TITLE
Add accumulate_with_remainder()

### PR DESCRIPTION
**Pull request by vm**

### CODE REVIEW

**Comment by Suor** [comment]
Looks way too specific, can't see how this is generally useful.

**Comment by Suor** [comment]
Reopen with usage examples if any.

**Comment by vm** [comment]
Useful for cases where you'd want to accumulate while knowing what is remaining (if it must be actionable).

```python
buffer = ''
items = []

for line in sys.stdin:
    for curr, remain in reversed(accumulate_with_remainder(line)):
        try:
            items.append(json.loads(buffer + tmp))
            buffer = remain
            break
        except ValueError:
            pass
    else:
        buffer += line
```

**Comment by Suor** [comment]
Maybe something like `heads()` or `tails()` will do the job for you:
```python
>>> heads('1234')
['1', '12', '123', '1234']
>>> tails('1234')
['1234', '234', '34', '4']
```
These are hypotetical, so don't try to import them yet :)

**Pull request closed without merging**
