### PR TITLE
Add set_in, update_in

### PR DESCRIPTION
**Pull request by swaroopch**
Analogous to Clojure's assoc-in, update-in

Follow-up to https://github.com/Suor/funcy/pull/28#issuecomment-77737258

### CODE REVIEW

**Comment by Suor** [comment]
Hello and thanks for your efforts.

You, however, implemented mutating `set_in()` and `update_in()`, which kind of not funcy scope. Funcys `set_in()` should behave like clojures `assoc-in`: create a new collection based on passed one, with a bit of it altered. 

Also, please, change argument names to be more in line with the rest of the library, like here - https://github.com/Suor/funcy/commit/e6bd6af1f803c0778ae8a6a335df6d58822727a7

**Comment by swaroopch** [comment]
@Suor, sorry for the late response, I didn't get an email notification for this.

Hmmm, to create a new collection, I would have to use `copy.deepcopy`, is that okay performance-wise? Or any other ideas?

Will change the arg names in the next push.

**Comment by Suor** [comment]
No deep copies, new collection should share parts with old one. That's the point. E.g.:
```python
d = {
    'a': {'x': 1, 'y': 2},
    'b': {'z': 3}
}
set_in(d, ['a', 'x'], 10) == {
    'a': {'x': 10, 'y': d['a']['y']},
    'b': d['b']
}
```

**Comment by Suor** [comment]
Do you need more help with this? Or more clarifications?

**Pull request closed without merging**
