### PR TITLE
Add function get_in

### PR DESCRIPTION
**Pull request by swaroopch**
Analogous to
http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/get-in

### CODE REVIEW

**Comment by Suor** [comment]
Hello Swaroop, and thanks for your interest and effort. Having `get_in()` will be nice, however, your implementation is not that efficient. I suggest you skip on recursion and go for simple for loop here. You also won't need `first`, `second` and `rest` this way.

**Comment by swaroopch** [comment]
@Suor I have rewritten to a simple `for` loop, please kindly review.

However, I am unclear about the reasoning though. Is recursion in Python inefficient?

**Comment by Suor** [comment]
Function calls are expensive relative to for loop. You usually don't care in app code, but this is low-level utility and library code, so it could matter for someone.

Additionally, `first()` and `second()` has safeguards built-in, which also add up. Also, with `list(rest(...))` you were creating unnecessary intermediate lists.

**Comment by Suor** [comment]
Are you up to adding accompanying functions `set_in()` and `update_in()`?

**Pull request merged**
