### PR TITLE
Add fixpoint function

### PR DESCRIPTION
**Pull request by poneill**
From the docs:

```fixpoint(f, x)
   
Finds the fixed point of ``x`` under ``f``, i.e. the ``y`` such that ``y = f^n(x) = f^(n+1)(x)``.  NB: it will not terminate if no fixed point exists.```

### CODE REVIEW

**Comment by poneill** [comment]
looks like CI is failing on 2.7 with: `tests/test_interface.py:67:20: W504 line break after binary operator`.  Doesn't seem obviously related to this PR but would be grateful for advice?

**Comment by Suor** [comment]
funcy is not about math.

**Comment by poneill** [comment]
Neither were any of the use cases in which I've needed it.  The function is an ancillary function to `iterate` that covers the common pattern: "repeatedly apply the function until you get the same thing out as you put in".  Many functions in the library, such as `flatten`, are actually examples of this pattern.  The only necessary mathematical concepts are function application and equality.

**Comment by poneill** [comment]
`fixpoint` is a very general function that captures the notion of "applying a function repeatedly until you can't meaningfully apply it any more".  It may be most helpful to think of it in terms of `iterate(f, x)`, which gives you the infinite sequence `x, f(x), f(f(x)), f(f(f(x)))...`.  Often, `f` and `x` are such that this sequence will be of the form `x_0, x_1, x_2, ..., x_n, x_n, x_n,
...`, with an infinitely repeating terminal value `x_n`.  
`fixpoint` gives you `x_n`.

To take a practical example, suppose you have a comment thread represented as a dictionary `d` where the keys are comment ids and the values are the ids of the respective parent comments.  Each comment can have multiple children, and some comments are top-level comments with no parent.  Suppose that, given an arbitrary comment, we want to find its top-level ancestor.  Then, given the `comment_id` of an arbitrary comment, we can find its top-level ancestor by writing:

```top_level_ancestor = fixpoint(lambda cid:d.get(cid, cid), comment_id)```

That is, we trace the parents through the dictionary until we can't go any further, whereupon we return the last `comment_id` we traversed.

Or suppose that we were trying to define `lflatten`.  Let's say that we could only manage to flatten a nested list by one level:

``` def lflatten1(xs): ys = [] for x in xs: if type(x) is list: for elem in x: ys.append(elem) else: ys.append(x) return ys ```

we could still define a full-fledged `lflatten` in terms of `fixpoint`.  In particular, we have:

``` def lflatten(xs): return fixpoint(lflatten1, xs) ```

That is, you can flatten an arbitrarily nested list by repeatedly flattening it one level at a time until you can't flatten it any further.  Many recursive functions are more natural to write in the fixpoint idiom, especially when they're somehow related to the notion of transitive closure.

The previous two examples show concrete use cases, but I also want to suggest that `fixpoint` is a quite generically powerful higher order function.  To see this, let's define [fold](https://en.wikipedia.org/wiki/Fold_(higher-order_function)) in terms of `fixpoint`.  We can write a left fold (right fold is necessarily similar) as follows:

``` def foldl(acc, f, xs): def fp(_acc_xs): _acc, _xs = _acc_xs if _xs == []: return (_acc, _xs) else: return (f(_acc, first(_xs)), rest(_xs)) return first(fixpoint(fp, (acc, xs))) ```

The only trick here is to lift the function `f` into a function `fp` that accepts the accumulator and input list as a tuple, and then extract the accumulator at the end.

**Comment by Suor** [comment]
More natural solution for first:
```python
top_level_ancestor = last(takewhile(bool, iterate(d.get, comment_id)))
```
Way more efficient `lflatten()` is already implemented.
There is no need to reinvent `reduce()`. And your implementation doesn't need `fixpoint()`:
```python
def foldl(acc, f, xs):
    if not xs:
        return acc
     else:
        return foldl(f(acc, first(xs)), f, rest(xs))  
        # The last line won't work for iterator xs BTW
```


There is no goal of implementing all FP in funcy, there is a goal to borrow FP ideas while practical and pythonic.

**Comment by poneill** [comment]
Ok, thanks for the feedback.

**Pull request closed without merging**
