### PR TITLE
Attribute pluck

### PR DESCRIPTION
**Pull request by volker48**
I found myself needing to pluck an attribute from a list of objects very frequently so I added a `pluck_attr` function. I also added it to the docs and added a test.

### CODE REVIEW

**Comment by Suor** [comment]
Hello Marcus and thank you for this contribution.

I have few consideration though:
1. Naming. I can't think of one word descriptive name, probably `attrs`? Not sure, do you have ideas? If we go for 2 words then isn't `attr_pluck` or `pluck_attrs` better?
2. Docs description. "list of values for ``name`` in each object" sounds a bit ambiguous.
3. You said you were needing it frequently. Can you add one of your uses as real-life example to docs? That's kind of funcy docs way :)

**Comment by volker48** [comment]
1. Yeah I wasn't a huge fan of giving it a two part name, but it was the firs thing that came to mind. I originally had attr_pluck then changed it to pluck_attr.
2. I'll update the docs. 
3. I'll add some examples.

**Comment by Suor** [comment]
1. `attrs` is confusing too. One could think you can pass object there and get its attributes. Making pluck "clever" is not an option, object could both have attributes and items and list could be heterogenous, this will be a nightmare. So it either `pluck_attr` or `pluck_attrs` I guess, which sounds better?

**Comment by volker48** [comment]
Yeah I agree making pluck clever is a bad idea. I like pluck_attrs.

As far as the examples, where should I place it in the docs? Just beneath the definition of pluck_attrs?

**Comment by Suor** [comment]
Yes, the same way as everywhere else in docs.
Can be used to do some clever thing:
```python
... pluck_attrs(...) ...
```

**Comment by volker48** [comment]
I renamed to pluck_attrs and added a small example to the documentation.

**Comment by Suor** [comment]
Merged, thanks

**Comment by Suor** [comment]
Renamed back to `pluck_attr()` in c2442995f88f0047bbfb20b6d27a02880f4fe778.

Also, do you now you can do:
```python
ids = User.objects.values_list('id', flat=True)
```
This makes docs example a bit superfluous.

**Pull request merged**
