### PR TITLE
New function complementary to project()

### PR DESCRIPTION
**Pull request by rozenbom**
It would be great to have a function complementary to project(): construct a new dict from a given mapping which keys are **not** in a given sequence.

### CODE REVIEW

**Comment by Suor** [comment]
There are few things stopping me right now:
1. Not sure I want to extend funcy much more.
2. `throw` is a no go name, smells like exception.
3. Maybe adding a complementary func to `select_keys()` would be a better way to extend funcy interface.

On last one. Instead of `project()` one can use:
```python
select_keys(set(keys), mapping)
```
It has several upsides: it's more universal, more efficient when `keys` is large, easier to use in `partial()`. And a downside of being longer. So your use case can be written as:
```python
select_keys(complement(set(keys)), mapping) 
# or say
reject_keys(set(keys), mapping) 
```
Your use case seems like less common than one of `project()`, so missing special case func or just a longer way to do thing could be ok. So I let it hang for now.

**Comment by rozenbom** [comment]
Sure it's can be achieved using existing functional but usually (from my humble experience) necessity to explicitly make sets and call complement is a show-stopper and people end up with a dict comprehension. Anyway thank you for the feedback.

**Comment by Suor** [comment]
Dict comprehension is a good solution too. Sometimes it's makes better code.

**Comment by Suor** [comment]
Added as `omit()`. Thanks for PR.

**Comment by rozenbom** [comment]
Thank you!

**Pull request merged**
